apiVersion: v2
name: drone-tm
description: Drone Tasking Manager - coordinated drone mapping
version: "0.4.0"
appVersion: "2026.1.1"
maintainers:
  - email: sysadmin@hotosm.org
    name: HOTOSM
home: https://github.com/hotosm/drone-tm
icon: https://drone.hotosm.org/favicon.png
dependencies:
  - name: postgresql
    version: 15.2.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    alias: postgresql
  - name: dragonfly
    version: v1.36.0
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    alias: dragonfly
