repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [pre-commit, pre-push, manual]

      - id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [pre-commit, pre-push, manual]

      - id: detect-aws-credentials
        name: detect aws credentials
        description: detects *your* aws credentials from the aws cli credentials file.
        entry: detect-aws-credentials
        language: python
        types: [text]
        args:
          - "--allow-missing-credentials"

      - id: detect-private-key
        name: detect private key
        description: detects the presence of private keys.
        entry: detect-private-key
        language: python
        types: [text]

      - id: check-executables-have-shebangs
        name: check that executables have shebangs
        description: ensures that (non-binary) executables have a shebang.
        entry: check-executables-have-shebangs
        language: python
        types: [text, executable]
        stages: [pre-commit, pre-push, manual]

      - id: check-shebang-scripts-are-executable
        name: check that scripts with shebangs are executable
        description: ensures that (non-binary) files with a shebang are executable.
        entry: check-shebang-scripts-are-executable
        language: python
        types: [text]
        stages: [pre-commit, pre-push, manual]

      - id: check-json
        name: check json
        description: checks json files for parseable syntax.
        entry: check-json
        language: python
        files: \.(json|template)$
        types: [json]

      - id: check-merge-conflict
        name: check for merge conflicts
        description: checks for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: python
        types: [text]

      - id: check-yaml
        name: YAML File check
        description: Checks if YAML File is valid and there are not any indention errors.
        exclude: ^chart/(?:.*/)*.*$
        args: [--unsafe]

      - id: check-added-large-files
        name: check for added large files
        description: prevents giant files from being committed.
        entry: check-added-large-files
        language: python
        stages: [pre-commit, pre-push, manual]
        args: ["--maxkb=10240"]

  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.15.9"
    hooks:
      # Run the linter
      - id: ruff
        files: ^src/backend/(?:.*/)*.*$
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format
        files: ^src/backend/(?:.*/)*.*$

  # Deps: ensure Python uv lockfile is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.3
    hooks:
      - id: uv-lock
        files: src/backend/pyproject.toml
        args: [--project, src/backend]

  # Upgrade: upgrade Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  # # Lint: code cognitive complexity
  # - repo: https://github.com/rohaquinlop/complexipy-pre-commit
  #   rev: v5.1.0
  #   hooks:
  #     - id: complexipy

  # Spelling: Checks for common misspellings in text files.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        types: [text]
        args: [--toml, src/backend/pyproject.toml]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        files: ^
        entry: bash -c 'test "$#" -gt 0 && oxfmt --write "$@" || exit 0' --
        language: node
        "types": [text]
        additional_dependencies: ["oxfmt@0.35.0"]
        args:
          [
            "!cla.json",
            "!src/qfield-plugin/**",
            "!src/pnpm-lock.yaml",
            "!src/pnpm-workspace.yaml",
            "!chart/**",
            "!CHANGELOG.md",
            "!CONTRIBUTING.md",
            "!src/backend/tests/test_data/**",
          ]

  # Lint: GH Workflows
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        args: [-ignore, SC]

  # # Lint: Markdown
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.47.0
  #   hooks:
  #     - id: markdownlint
  #       args:
  #         [
  #           --fix,
  #           --disable,
  #           MD059,
  #           --ignore,
  #           CHANGELOG.md,
  #           --ignore,
  #           .github,
  #           --ignore,
  #           src/backend/packages/drone-flightplan/CHANGELOG.md,
  #           --ignore,
  #           src/backend/packages/drone-flightplan/LICENSE.md,
  #         ]
