networks:
  dtm-network:
    name: dtm-network

volumes:
  odm-media:
  odm-db-data:

services:
  # This container does the actual imagery processing (not persistent, scalable)
  odm-api:
    image: docker.io/opendronemap/nodeodm:3.5.3
    # This is hardcoded by default
    hostname: webodm-node-odm-1
    container_name: odm-api
    networks:
      - dtm-network
    restart: unless-stopped
    oom_score_adj: 500

  # UI to coordinate queueing of tasks and display of output
  odm-web:
    image: docker.io/opendronemap/webodm_webapp:2.5.5
    container_name: odm-web
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh odm-db /webodm/wait-for-it.sh -t 0 odm-broker:6379 -- /webodm/start.sh\""
    volumes:
      - odm-media:/webodm/app/media:z
    ports:
      - "${WO_PORT}:8000"
    depends_on:
      odm-worker:
        condition: service_started
    env_file:
      - .env
    networks:
      - dtm-network
    restart: unless-stopped
    oom_score_adj: 0

  # Instance of WebODM that uses Celery to manage processing jobs
  odm-worker:
    image: docker.io/opendronemap/webodm_webapp:2.5.5
    container_name: odm-worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh odm-db /webodm/wait-for-it.sh -t 0 odm-broker:6379 -- /webodm/wait-for-it.sh -t 0 odm-web:8000 -- /webodm/worker.sh start"
    volumes:
      - odm-media:/webodm/app/media:z
    depends_on:
      odm-db:
        condition: service_started
      odm-broker:
        condition: service_started
    env_file:
      - .env
    networks:
      - dtm-network
    restart: unless-stopped
    oom_score_adj: 250

  # Redis broker to manage job queue
  odm-broker:
    image: docker.io/redis:7.4.1
    container_name: odm-broker
    networks:
      - dtm-network
    restart: unless-stopped
    oom_score_adj: -500

  # Stores data related to the web instance & queueing
  odm-db:
    image: docker.io/opendronemap/webodm_db:latest
    container_name: odm-db
    volumes:
      - odm-db-data:/var/lib/postgresql/data:Z
    ports:
      - 5999:5432
    networks:
      - dtm-network
    restart: unless-stopped
    oom_score_adj: -100
