{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "drone-tm.fullname" . }}-migrations
  labels:
    {{- include "drone-tm.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "drone-tm.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "drone-tm.serviceAccountName" . }}
      containers:
        - name: migrations
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: {{ include "drone-tm.secretName" . }}
            {{- with .Values.backend.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
{{- end }}
