declare module '@hotosm/ui/dist/hotosm-ui';
declare module '@AuthLibs/web-component/dist/hanko-auth.esm.js';
declare module '*.png';
declare module '*.svg';
declare module '*.jpeg';
declare module '*.jpg';
declare module 'uuid';
declare module '@mapbox/mapbox-gl-draw-static-mode';
declare module 'mapbox-gl-draw-cut-line-mode';
