"""add overlap in projects table

Revision ID: 1ebfe5e4cf1c
Revises: 4b1534031978
Create Date: 2024-07-03 08:13:33.354101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ebfe5e4cf1c"
down_revision: Union[str, None] = "4b1534031978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("overlap", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "overlap")
    # ### end Alembic commands ###
