"""

Revision ID: 2453ee32bc4f
Revises: 2803924c6ff9
Create Date: 2024-11-29 05:15:04.384513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2453ee32bc4f"
down_revision: Union[str, None] = "2803924c6ff9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drone_altitudes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=False),
        sa.Column("max_altitude_ft", sa.Float(), nullable=False),
        sa.Column("max_altitude_m", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drone_altitudes")
    # ### end Alembic commands ###
