"""add odm_endpoint_used column to tasks table for custom endpoints

Revision ID: 3265acd2362a
Revises: a43e60e246c6
Create Date: 2026-07-21 18:49:27.339241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3265acd2362a"
down_revision: Union[str, None] = "a43e60e246c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("odm_endpoint_used", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "odm_endpoint_used")
    # ### end Alembic commands ###
