"""

Revision ID: 3293e9c98b2a
Revises: 06668eb5d14a
Create Date: 2024-07-10 04:52:41.412683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3293e9c98b2a"
down_revision: Union[str, None] = "06668eb5d14a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "task_status")
    op.add_column(
        "user_profile",
        sa.Column(
            "role",
            sa.Enum("PROJECT_CREATOR", "DRONE_PILOT", name="userrole"),
            nullable=True,
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("PROJECT_CREATOR", "DRONE_PILOT", "BOTH", name="userrole"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user_profile", "role")
    op.add_column(
        "tasks",
        sa.Column(
            "task_status",
            postgresql.ENUM(
                "READY",
                "LOCKED_FOR_MAPPING",
                "MAPPED",
                "LOCKED_FOR_VALIDATION",
                "VALIDATED",
                "INVALIDATED",
                "BAD",
                "SPLIT",
                name="taskstatus",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
