"""

Revision ID: 488158d3d5a8
Revises: 87b6f9d734e8
Create Date: 2024-08-07 05:15:38.875346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "488158d3d5a8"
down_revision: Union[str, None] = "87b6f9d734e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    finaloutput_enum = sa.Enum(
        "ORTHOPHOTO_2D",
        "ORTHOPHOTO_3D",
        "DIGITAL_TERRAIN_MODEL",
        "DIGITAL_SURFACE_MODEL",
        name="finaloutput",
    )
    finaloutput_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "final_output",
            sa.ARRAY(
                sa.Enum(
                    "ORTHOPHOTO_2D",
                    "ORTHOPHOTO_3D",
                    "DIGITAL_TERRAIN_MODEL",
                    "DIGITAL_SURFACE_MODEL",
                    name="finaloutput",
                )
            ),
            nullable=True,
        ),
    )
    op.add_column("projects", sa.Column("auto_lock_tasks", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "auto_lock_tasks")
    op.drop_column("projects", "final_output")
    # ### end Alembic commands ###
    finaloutput_enum = sa.Enum(
        "ORTHOPHOTO_2D",
        "ORTHOPHOTO_3D",
        "DIGITAL_TERRAIN_MODEL",
        "DIGITAL_SURFACE_MODEL",
        name="finaloutput",
    )
    finaloutput_enum.drop(op.get_bind())
