"""

Revision ID: 5d38e368b3d2
Revises: 87b6f9d734e8
Create Date: 2024-08-06 07:22:37.970226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d38e368b3d2"
down_revision: Union[str, None] = "87b6f9d734e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("forward_overlap_percent", sa.Float(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("side_overlap_percent", sa.Float(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("altitude_from_ground", sa.Float(), nullable=True)
    )
    op.drop_column("projects", "overlap_percent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "overlap_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("projects", "altitude_from_ground")
    op.drop_column("projects", "side_overlap_percent")
    op.drop_column("projects", "forward_overlap_percent")
    # ### end Alembic commands ###
