"""

Revision ID: 5d38e368b3d2
Revises: 87b6f9d734e8
Create Date: 2024-08-06 07:22:37.970226

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d38e368b3d2"
down_revision: str | None = "d862bfa31c36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("altitude_from_ground", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "altitude_from_ground")
    # ### end Alembic commands ###
