"""

Revision ID: 62a16e505bc3
Revises: bf26afac872d
Create Date: 2024-07-04 04:58:26.406871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62a16e505bc3"
down_revision: Union[str, None] = "bf26afac872d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("organization_name", sa.String(), nullable=True),
        sa.Column("organization_address", sa.String(), nullable=True),
        sa.Column("job_title", sa.String(), nullable=True),
        sa.Column("notify_for_projects_within_km", sa.SmallInteger(), nullable=True),
        sa.Column("experience_years", sa.SmallInteger(), nullable=True),
        sa.Column("drone_you_own", sa.String(), nullable=True),
        sa.Column("certified_drone_operator", sa.Boolean(), nullable=True),
        sa.Column("certificate", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    # ### end Alembic commands ###
