"""oam_upload_status

Revision ID: 7389d0d528c3
Revises: 7b6426a1bd67
Create Date: 2025-02-28 04:25:19.155531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7389d0d528c3"
down_revision: Union[str, None] = "7b6426a1bd67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type first
    oamuploadstatus = sa.Enum(
        "NOT_STARTED", "UPLOADING", "UPLOADED", "FAILED", name="oamuploadstatus"
    )
    oamuploadstatus.create(op.get_bind(), checkfirst=True)

    # Then add the column with a default value
    op.add_column(
        "projects",
        sa.Column(
            "oam_upload_status",
            oamuploadstatus,
            nullable=False,
            server_default=sa.text("'NOT_STARTED'::oamuploadstatus"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "oam_upload_status")
    sa.Enum(name="oamuploadstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
