"""oam-api-token

Revision ID: 7b6426a1bd67
Revises: f78cde896334
Create Date: 2025-02-11 05:39:04.833623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b6426a1bd67"
down_revision: Union[str, None] = "f78cde896334"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "image_processing_status",
        existing_type=postgresql.ENUM(
            "NOT_STARTED",
            "PROCESSING",
            "SUCCESS",
            "FAILED",
            name="imageprocessingstatus",
        ),
        nullable=True,
        existing_server_default=sa.text("'NOT_STARTED'::imageprocessingstatus"),
    )
    op.add_column(
        "user_profile", sa.Column("oam_api_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "oam_api_token")
    op.alter_column(
        "projects",
        "image_processing_status",
        existing_type=postgresql.ENUM(
            "NOT_STARTED",
            "PROCESSING",
            "SUCCESS",
            "FAILED",
            name="imageprocessingstatus",
        ),
        nullable=False,
        existing_server_default=sa.text("'NOT_STARTED'::imageprocessingstatus"),
    )
    # ### end Alembic commands ###
