"""deadline for projects

Revision ID: 832089d4a1de
Revises: 88ae62ec8876
Create Date: 2024-07-13 05:01:32.713490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '832089d4a1de'
down_revision: Union[str, None] = '88ae62ec8876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deadline')
    # ### end Alembic commands ###
