"""

Revision ID: 87b6f9d734e8
Revises: 9d01411fd221
Create Date: 2024-07-26 05:18:16.267171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "87b6f9d734e8"
down_revision: Union[str, None] = "9d01411fd221"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_column("projects", "slug")
    # ### end Alembic commands ###
