"""

Revision ID: 88ae62ec8876
Revises: 3293e9c98b2a
Create Date: 2024-07-10 05:21:58.749137

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88ae62ec8876"
down_revision: str | None = "3293e9c98b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
