"""

Revision ID: 9d01411fd221
Revises: acee47666167
Create Date: 2024-07-20 13:35:29.634665

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "9d01411fd221"
down_revision: Union[str, None] = "acee47666167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "projects",
        "no_fly_zones",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "no_fly_zones",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
