"""scaleodm reconcile, add index to speed up cron scan

Revision ID: a43e60e246c6
Revises: b2d6f3a91c47
Create Date: 2026-07-21 17:42:52.327238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a43e60e246c6"
down_revision: Union[str, None] = "b2d6f3a91c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tasks_odm_inflight",
        "tasks",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("odm_task_uuid IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tasks_odm_inflight",
        table_name="tasks",
        postgresql_where=sa.text("odm_task_uuid IS NOT NULL"),
    )
    # ### end Alembic commands ###
