"""index task lookups used by the project list filters

Revision ID: a55b375601fc
Revises: 3265acd2362a
Create Date: 2026-08-22 14:35:12.067971

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a55b375601fc"
down_revision: str | None = "3265acd2362a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_task_events_task_id_created_at",
        "task_events",
        ["task_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_tasks_project_id", "tasks", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_project_id", table_name="tasks")
    op.drop_index("ix_task_events_task_id_created_at", table_name="task_events")
    # ### end Alembic commands ###
