"""

Revision ID: ac09917990dc
Revises: 62a16e505bc3
Create Date: 2024-07-04 10:52:52.166220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac09917990dc"
down_revision: str | None = "62a16e505bc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "dem_url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "dem_url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
