"""

Revision ID: b4338a93f7bb
Revises: aec0d408df01
Create Date: 2024-10-01 03:44:03.666090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4338a93f7bb"
down_revision: str | None = "aec0d408df01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_events", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_events", "updated_at")
    # ### end Alembic commands ###
