"""

Revision ID: b574d3a13e62
Revises: 87b6f9d734e8
Create Date: 2024-08-05 15:02:26.464109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b574d3a13e62'
down_revision: Union[str, None] = '87b6f9d734e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

final_output_enum = sa.Enum(
    'ORTHOPHOTO_2D',
    'ORTHOPHOTO_3D',
    'DIGITAL_TERRAIN_MODEL',
    'DIGITAL_SURFACE_MODEL',
    name='finaloutput'
)


def upgrade() -> None:
    final_output_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('final_output', sa.Enum('ORTHOPHOTO_2D', 'ORTHOPHOTO_3D', 'DIGITAL_TERRAIN_MODEL', 'DIGITAL_SURFACE_MODEL', name='finaloutput'), nullable=True))
    op.add_column('projects', sa.Column('auto_lock_tasks', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_lock_tasks')
    op.drop_column('projects', 'final_output')
    # ### end Alembic commands ###
    final_output_enum.drop(op.get_bind())
