"""

Revision ID: c1ee756a3449
Revises: 87b6f9d734e8
Create Date: 2024-08-06 11:06:12.267127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1ee756a3449"
down_revision: Union[str, None] = "87b6f9d734e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("final_output", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("projects", sa.Column("auto_lock_tasks", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "auto_lock_tasks")
    op.drop_column("projects", "final_output")
    # ### end Alembic commands ###
