"""

Revision ID: d202ea539f6d
Revises: e23c05f21542
Create Date: 2024-12-26 08:11:00.011691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d202ea539f6d"
down_revision: Union[str, None] = "e23c05f21542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_events",
        "state",
        existing_type=postgresql.ENUM(
            "REQUEST_FOR_MAPPING",
            "UNLOCKED_TO_MAP",
            "LOCKED_FOR_MAPPING",
            "UNLOCKED_TO_VALIDATE",
            "LOCKED_FOR_VALIDATION",
            "UNLOCKED_DONE",
            "UNFLYABLE_TASK",
            "IMAGE_UPLOADED",
            "IMAGE_PROCESSING_FAILED",
            "IMAGE_PROCESSING_STARTED",
            "IMAGE_PROCESSING_FINISHED",
            name="state",
        ),
        nullable=False,
    )
    op.add_column("tasks", sa.Column("total_area_sqkm", sa.Float(), nullable=True))
    op.add_column("tasks", sa.Column("flight_time_minutes", sa.Float(), nullable=True))
    op.add_column("tasks", sa.Column("flight_distance_km", sa.Float(), nullable=True))
    op.add_column(
        "tasks", sa.Column("total_image_uploaded", sa.SmallInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "total_image_uploaded")
    op.drop_column("tasks", "flight_distance_km")
    op.drop_column("tasks", "flight_time_minutes")
    op.drop_column("tasks", "total_area_sqkm")
    op.alter_column(
        "task_events",
        "state",
        existing_type=postgresql.ENUM(
            "REQUEST_FOR_MAPPING",
            "UNLOCKED_TO_MAP",
            "LOCKED_FOR_MAPPING",
            "UNLOCKED_TO_VALIDATE",
            "LOCKED_FOR_VALIDATION",
            "UNLOCKED_DONE",
            "UNFLYABLE_TASK",
            "IMAGE_UPLOADED",
            "IMAGE_PROCESSING_FAILED",
            "IMAGE_PROCESSING_STARTED",
            "IMAGE_PROCESSING_FINISHED",
            name="state",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
