"""

Revision ID: d862bfa31c36
Revises: 87b6f9d734e8
Create Date: 2024-08-07 07:39:34.816982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d862bfa31c36"
down_revision: Union[str, None] = "87b6f9d734e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    finaloutput_enum = sa.Enum(
        "ORTHOPHOTO_2D",
        "ORTHOPHOTO_3D",
        "DIGITAL_TERRAIN_MODEL",
        "DIGITAL_SURFACE_MODEL",
        name="finaloutput",
    )
    finaloutput_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("front_overlap", sa.Float(), nullable=True))
    op.add_column("projects", sa.Column("side_overlap", sa.Float(), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "final_output",
            sa.ARRAY(
                sa.Enum(
                    "ORTHOPHOTO_2D",
                    "ORTHOPHOTO_3D",
                    "DIGITAL_TERRAIN_MODEL",
                    "DIGITAL_SURFACE_MODEL",
                    name="finaloutput",
                )
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "requires_approval_from_manager_for_locking", sa.Boolean(), nullable=True
        ),
    )
    op.drop_column("projects", "overlap_percent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "overlap_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("projects", "requires_approval_from_manager_for_locking")
    op.drop_column("projects", "final_output")
    op.drop_column("projects", "side_overlap")
    op.drop_column("projects", "front_overlap")
    # ### end Alembic commands ###
    finaloutput_enum = sa.Enum(
        "ORTHOPHOTO_2D",
        "ORTHOPHOTO_3D",
        "DIGITAL_TERRAIN_MODEL",
        "DIGITAL_SURFACE_MODEL",
        name="finaloutput",
    )
    finaloutput_enum.drop(op.get_bind())
