"""Initial migration.

Revision ID: df7ed4487ab6
Revises:
Create Date: 2024-06-13 16:10:40.042674

"""
import geoalchemy2
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df7ed4487ab6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("profile_img", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("email_address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_address"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("per_task_instructions", sa.String(), nullable=True),
        sa.Column("location_str", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "outline",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ARCHIVED", "PUBLISHED", "DRAFT", name="projectstatus"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", "INVITE_ONLY", name="projectvisibility"),
            nullable=False,
        ),
        sa.Column(
            "mapper_level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="mappinglevel"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("URGENT", "HIGH", "MEDIUM", "LOW", name="projectpriority"),
            nullable=True,
        ),
        sa.Column(
            "task_split_type",
            sa.Enum(
                "DIVIDE_ON_SQUARE",
                "CHOOSE_AREA_AS_TASK",
                "TASK_SPLITTING_ALGORITHM",
                name="tasksplittype",
            ),
            nullable=True,
        ),
        sa.Column("task_split_dimension", sa.SmallInteger(), nullable=True),
        sa.Column("total_tasks", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name="fk_users"),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], name="fk_organisations"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_geometry", "projects", ["outline"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        op.f("ix_projects_mapper_level"), "projects", ["mapper_level"], unique=False
    )
    op.create_index(
        op.f("ix_projects_organisation_id"),
        "projects",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("project_task_index", sa.Integer(), nullable=True),
        sa.Column("project_task_name", sa.String(), nullable=True),
        sa.Column(
            "outline",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "task_status",
            sa.Enum(
                "READY",
                "LOCKED_FOR_MAPPING",
                "MAPPED",
                "LOCKED_FOR_VALIDATION",
                "VALIDATED",
                "INVALIDATED",
                "BAD",
                "SPLIT",
                name="taskstatus",
            ),
            nullable=True,
        ),
        sa.Column("locked_by", sa.BigInteger(), nullable=True),
        sa.Column("mapped_by", sa.BigInteger(), nullable=True),
        sa.Column("validated_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["locked_by"], ["users.id"], name="fk_users_locked"),
        sa.ForeignKeyConstraint(["mapped_by"], ["users.id"], name="fk_users_mapper"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name="fk_users_validator"
        ),
        sa.PrimaryKeyConstraint("id", "project_id"),
    )
    op.create_index(op.f("ix_tasks_locked_by"), "tasks", ["locked_by"], unique=False)
    op.create_index(op.f("ix_tasks_mapped_by"), "tasks", ["mapped_by"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_validated_by"), "tasks", ["validated_by"], unique=False
    )
    op.create_table(
        "task_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "RELEASED_FOR_MAPPING",
                "LOCKED_FOR_MAPPING",
                "MARKED_MAPPED",
                "LOCKED_FOR_VALIDATION",
                "VALIDATED",
                "MARKED_INVALID",
                "MARKED_BAD",
                "SPLIT_NEEDED",
                "RECREATED",
                "COMMENT",
                name="taskaction",
            ),
            nullable=False,
        ),
        sa.Column("action_text", sa.String(), nullable=True),
        sa.Column("action_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "project_id"], ["tasks.id", "tasks.project_id"], name="fk_tasks"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_users"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_history_composite",
        "task_history",
        ["task_id", "project_id"],
        unique=False,
    )
    op.create_index(
        "idx_task_history_project_id_user_id",
        "task_history",
        ["user_id", "project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_history_project_id"), "task_history", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_history_user_id"), "task_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_history_user_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_project_id"), table_name="task_history")
    op.drop_index("idx_task_history_project_id_user_id", table_name="task_history")
    op.drop_index("idx_task_history_composite", table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_tasks_validated_by"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_mapped_by"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_locked_by"), table_name="tasks")
    op.drop_index("idx_tasks_outline", table_name="tasks", postgresql_using="gist")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_projects_organisation_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_mapper_level"), table_name="projects")
    op.drop_index(
        "idx_projects_outline", table_name="projects", postgresql_using="gist"
    )
    op.drop_index(
        "idx_projects_centroid", table_name="projects", postgresql_using="gist"
    )
    op.drop_index("idx_geometry", table_name="projects", postgresql_using="gist")
    op.drop_table("projects")
    op.drop_table("users")
    op.drop_table("organisations")
    # ### end Alembic commands ###
