"""image_processing_status

Revision ID: f78cde896334
Revises: b18103ac4ab7
Create Date: 2025-01-15 05:11:08.788485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f78cde896334"
down_revision: Union[str, None] = "b18103ac4ab7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "image_processing_status",
            sa.Enum(
                "NOT_STARTED",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                name="imageprocessingstatus",
            ),
            nullable=False,
            server_default=sa.text("'NOT_STARTED'"),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "image_processing_status")
    # ### end Alembic commands ###
