"""

Revision ID: f87adf188a16
Revises: 2b92f8a9bbec
Create Date: 2024-08-27 04:16:16.655935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f87adf188a16"
down_revision: Union[str, None] = "2b92f8a9bbec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "image_url")
    # ### end Alembic commands ###
