// Mobile bottom sheet; desktop layout turns these operations into no-ops.

export type Detent = "peek" | "half" | "full";

const ORDER: Detent[] = ["peek", "half", "full"];

const DESKTOP = window.matchMedia("(min-width: 900px)");

export interface Sheet {
  detent(): Detent;
  setDetent(next: Detent): void;
  remeasure(): void;
  collapseForMap(): void;
  restore(): void;
}

const SETTLE_MS = 300;

const GHOST_CLICK_MS = 500;

const DRAG_COMMIT_PX = 60;

export function createSheet(pane: HTMLElement, handle: HTMLElement, onResize: () => void): Sheet {
  let detent: Detent = "half";
  let restoreTo: Detent | null = null;
  let settleTimer: ReturnType<typeof setTimeout> | undefined;

  const isSheet = () => !DESKTOP.matches;

  function measurePeek(): number {
    const chrome = [".sheet-handle", ".step-rail", ".step-footer"]
      .map((selector) => pane.querySelector<HTMLElement>(selector)?.offsetHeight ?? 0)
      .reduce((total, height) => total + height, 0);
    return Math.round(chrome);
  }

  function syncPeekVar(): void {
    if (!isSheet()) return;
    document.documentElement.style.setProperty("--sheet-peek", `${measurePeek()}px`);
  }

  // Refit only after the height transition reaches its final position.
  function afterSettled(run: () => void): void {
    clearTimeout(settleTimer);
    settleTimer = setTimeout(run, SETTLE_MS);
  }

  function apply(next: Detent): void {
    detent = next;
    document.documentElement.dataset.sheet = next;
    handle.setAttribute("aria-expanded", String(next !== "peek"));
    afterSettled(onResize);
  }

  let dragFrom: { y: number; height: number; detent: Detent } | null = null;
  let moved = false;
  let pointerEndedAt = 0;

  handle.addEventListener("pointerdown", (event) => {
    if (!isSheet()) return;
    dragFrom = { y: event.clientY, height: pane.getBoundingClientRect().height, detent };
    moved = false;
    handle.setPointerCapture(event.pointerId);
    pane.classList.add("dragging");
  });

  handle.addEventListener("pointermove", (event) => {
    if (!dragFrom) return;
    const delta = dragFrom.y - event.clientY;
    if (Math.abs(delta) > 4) moved = true;
    const height = clamp(dragFrom.height + delta, minHeight(), maxHeight());
    pane.style.setProperty("--sheet-drag", `${height}px`);
  });

  const endDrag = (event: PointerEvent) => {
    if (!dragFrom) return;
    const height = pane.getBoundingClientRect().height;
    const from = dragFrom.detent;
    const travel = height - dragFrom.height;
    dragFrom = null;
    try {
      handle.releasePointerCapture(event.pointerId);
    } catch {
      /* already released */
    }
    pane.classList.remove("dragging");
    pane.style.removeProperty("--sheet-drag");
    pointerEndedAt = Date.now();
    apply(moved ? snapTarget(height, from, travel) : cycle(detent));
  };

  handle.addEventListener("pointerup", endDrag);
  handle.addEventListener("pointercancel", endDrag);

  handle.addEventListener("click", () => {
    if (!isSheet()) return;
    // pointerup already handles the click generated by a touch gesture.
    if (Date.now() - pointerEndedAt < GHOST_CLICK_MS) return;
    apply(cycle(detent));
  });

  handle.addEventListener("keydown", (event) => {
    if (!isSheet()) return;
    const step = event.key === "ArrowUp" ? 1 : event.key === "ArrowDown" ? -1 : 0;
    if (!step) return;
    event.preventDefault();
    const index = ORDER.indexOf(detent) + step;
    if (index >= 0 && index < ORDER.length) apply(ORDER[index]);
  });

  function minHeight(): number {
    return measurePeek();
  }

  function maxHeight(): number {
    const resolved = Number.parseFloat(getComputedStyle(pane).maxHeight);
    return Number.isFinite(resolved) ? resolved : window.innerHeight * 0.92;
  }

  function heightOf(target: Detent): number {
    if (target === "peek") return minHeight();
    if (target === "full") return maxHeight();
    return window.innerHeight * 0.55;
  }

  function nearestDetent(height: number): Detent {
    return ORDER.reduce((best, candidate) =>
      Math.abs(heightOf(candidate) - height) < Math.abs(heightOf(best) - height) ? candidate : best,
    );
  }

  // A committed drag advances one detent even if the nearest height is unchanged.
  function snapTarget(height: number, from: Detent, travel: number): Detent {
    const nearest = nearestDetent(height);
    if (nearest !== from || Math.abs(travel) < DRAG_COMMIT_PX) return nearest;
    const index = ORDER.indexOf(from) + Math.sign(travel);
    return ORDER[Math.min(ORDER.length - 1, Math.max(0, index))];
  }

  const onViewportChange = () => {
    syncPeekVar();
    onResize();
  };
  window.addEventListener("resize", onViewportChange);
  window.addEventListener("orientationchange", onViewportChange);
  DESKTOP.addEventListener("change", onViewportChange);
  syncPeekVar();
  apply(detent);

  return {
    detent: () => detent,

    remeasure: syncPeekVar,

    setDetent(next) {
      syncPeekVar();
      if (isSheet()) apply(next);
    },

    collapseForMap() {
      if (!isSheet() || detent === "peek") return;
      restoreTo ??= detent;
      apply("peek");
    },

    restore() {
      if (!isSheet() || !restoreTo) return;
      const target = restoreTo;
      restoreTo = null;
      apply(target);
    },
  };
}

function cycle(current: Detent): Detent {
  return ORDER[(ORDER.indexOf(current) + 1) % ORDER.length];
}

function clamp(value: number, low: number, high: number): number {
  return Math.min(high, Math.max(low, value));
}
