name: Build and Deploy

on:
  # Push includes PR merge
  push:
    branches:
      - main
      - staging
      - dev
    paths:
      # Workflow is triggered only if src changes
      - src/**
  # Allow manual trigger
  workflow_dispatch:

jobs:
  backend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.4.1
    with:
      context: ./src/backend
      build_target: service
      image_name: ghcr.io/${{ github.repository }}/backend
      dockerfile: Dockerfile
      scan_image: false
    secrets: inherit

  frontend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.4.1
    needs:
      - extra-vars
    with:
      context: ./src/frontend
      build_target: prod
      image_name: ghcr.io/${{ github.repository }}/frontend
      dockerfile: Dockerfile
      scan_image: false
    secrets: inherit

  deploy_to_vm:
    name: Deploy to VM
    needs:
      - frontend-build
      - backend-build
    uses: hotosm/gh-workflows/.github/workflows/remote_deploy_just.yml@3.4.1
    with:
      environment: ${{ github.ref_name == 'dev' && 'develop' || github.ref_name }}
      # Note we set build="false", as we already built in the step above
      command: start prod ${{ github.ref_name }} "false"
      example_env_file_path: .env.example
    secrets: inherit
