# We add a label `repo:repo-name` to each new issue,
# for easier tracking in external systems

name: 🏷️ Issue Label

on:
  issues:
    types:
      - opened

jobs:
  issue-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: repo:drone-tm
