name: Test Backend

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/backend/**"
      - "tasks/test/**"
      - ".github/workflows/test.yml"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "src/backend/**"
      - "tasks/test/**"
      - ".github/workflows/test.yml"

  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/just.yml@4.0.0
    with:
      environment: "test"
      command: "test backend"
    secrets: inherit
